language: node_js
node_js:
- '12'
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: tQsWGCyDc8aIrRz2pobvpAfeaVMqxpLWcsH1gDarWMIC/7hovmQ1pY/jhRQ9BGtnhuli7RCz5WD9JmP6UY4bTLUYXAmuPaimAhap3eJJ3J0WEoUepGgpXvOGNnw3EYuHcsi5aShaX7M88B5BBmS3a3tqCikFiDhYaFdKzt1YqZEXMaNzwdDFiyBLvQp8x1Nv7MOMuYMZwptXO3xTWSUjKRSKhoIkNWmvIgpiFnYd6MTNhrnb1CCZRw2oya8v9FMK2xp7tawZKD8XWmbGsOvr+yKtTlFtjXZ/69lvr9lsGsGA1drANMjVEFopgXWhFZj7kUkIAw4Fn7uMLQ/Os5WQiKdyDDrJa+5pz0ZSB5rbmkZa7anMgbXrapqUJ2Rs0sBIlKLoLj22C4tVH+eGoaaR2HOVsjCtD+7yiGHYDjemSzsY5Wsqe19BLCJIJo1BoOViH7WRWYxCmPKxmV8eWZYeNRWm2YZZ0GSPhvaPDhK3Cj+YQFhKkhKilPVeeV+sTf1dbDoxj8MxsbHu6kcf9FRf2/cj6FRYJMpw9Sq4DWqbmYdWnqqSfWdeUTV8wMF9DOr0IZeMRjrypr6tFbuDRHq187QCagIItfKFznpkZEwVt3arhSgulDBTyK/F1Ak9f1jUNRntn9q2wgK5+01JkPzf+zBw+1xYP0vBQ8eQC0cy6HU=
