language: node_js
node_js:
  - "8"
script:
  - npm run build
after_success:
  - cd dist; zip -r ../nielsgerritsen.zip *; cd ..
  - "curl -F 'data=@nielsgerritsen.zip' -H 'X-Key: '$DEPLOY_KEY -H 'X-ExtractTo: nielsgerritsen' https://carehr.nl/deploy/"
