language: node_js
node_js:
  - "7"
cache: yarn
script:
  - ./node_modules/.bin/bower install
  - ./node_modules/.bin/gulp build
after_success: ./node_modules/.bin/gulp ftp --user $FTP_USER --password $FTP_PASSWORD
