language: node_js
install:
- npm install
- bower install
script:
- gulp build
env:
  global:
    - secure: GGwGi4bYWBb06kTjQLF14ut/W7S3ecivE3sRMEVkIl07HLbVnZrJ2JeLzZdLUuUh1MAiF7/IT6wI5sqB9KHOltSjhwdUL50YYHewZvIEcs9jR166qZnRtM9xKchAtOuGwMM4lvrZ+t1mB3RNN6EBhAt6PX2YcnRDTklZPUDGuHQVMql/Mw1SfM0qBinK2kuIGYhT6YmZW2uCsy0n3VCZ+PkHnETX3JUZMe+Oic7PX0T5rOkTciMdUdHDkjm0SM+TMYhOHbbekz9CQRGu3PH/M5RJSGOPwi/KqGsr1svtxvv7C2V+szKk5VKRJxzZdd6zrZ95yzsYPlpwZWqNXcYb+YByahj8pAq6gc1BTKcmwMIhzS5I9KdNE7u98N9Rz7EUjhHdZul60EakT+hbr4THBsTZv6auk79gc74NVMRtn2uaXu72n9jmn0GR6FZdOFlqLndof0bIEKDOUkzNfpvN3jGiFSCaCuQlhjTxva9A7PYXTz5to8RsTSthuXMBtRN6iAUnaFyu3X3jmIxZsdBjyEj7CJcUDxz6i3UnedRtXAdzXLCjbMVROamJ1/cbqZnmR0/c/MAbGLWoyJGYXTT7S/Ayged43zMSXg6h74/f+II+0Ca1Z8stXH8uXS/7dX66xlOuuBmI+QZj/e40EATbvywYRjzveIHbZC8U+ZyyPgc=
    - secure: aPFBonqHCD/mkoXAVYzg7ha358Bxvpm7uzOsbiLBVzmkQaLYplEhVH6RsYxDhWC+D3Tqqzx38AklXxgASJwLQcgzNw5iWHEFegi5gtL8a58Ae8kbuIViscdJ/MVohdbyX16dZ5T+sdriKwGIZPTmGkaV+6XplCTlo2W2pjpbTdUQYWcvAWPksc5CzdfAKjowfVMsiX7K2fhJMNPQcHyzGl22EwtTd+Mdbz3i8E2C0Dv7APWmdvEn5DhBQUR24IXqBKrn277RXhlbj4fz0dpGn/sbsGuQtwn1bULpsN2WyfRuVZsuK7QbKyDc0IOwOMIf09zefXrx0xtldeVRzx7uBY7ZXYjp8o8ffEtIwohO106DcOrAa24evyDa2SzwMVP3Ksr8aXnviMBzkx//XY0sDwyZEoq/+GTRmP8SKgW1YH4TCmQCVJxF3d7oqypJHmwvRkf+V18/+u1IZukyN+hkUxUprAwDD26CydHUBnkgLzQydlWi1tifDrkUQkHazsjT2wmyAGEFT7Fs6+fxLoERpCCKhC0HTp666lBokNgBYYP325XRPVApEWUn/MMaY0kl1Bik4QK6IfYzWhNZH2NS1Ot1s1tDLpcPV54phkgfLHoZcDyfLTplIr6JzlaJkz1bhDfGpdH5GUQFJJbb6TFjfTLWljyvy0TUBI7XXNemv/s=
after_success: 
  - cd dist
  - find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://carehr.nl/public_html/nielsgerritsen/{} \;
